version: "3"

services:
  redis:
    image: 'redis:alpine'
    volumes:
      - 'redis:/data'
    env_file:
      - ./project.env
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
  sql:
    build: ./sql
    ports:
      - '54321:5432'
    platform: linux/x86_64
    volumes:
      - sql:/var/lib/postgresql/data/
    env_file:
      - ./project.env
  node:
    build: backend
    env_file:
      - project.env
    ports:
      - '8080:4200'
    user: "node"
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
volumes:
  sql:
    driver: local
  redis:
    driver: local